const projects = [
    {
        id: 1,
        key: 'samsung',
        title: ['운전자플랜', '실손보험', '건강보험', '자녀보험'],
        responsive : 'each',
        code: 'yes',
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['driver/samsung-driver-pc.png',
                'expense/samsung-expense-pc.png',
                'health/samsung-health-pc.png',
                'superstar/samsung-superstar-pc.png',
                ],
        moImg: ['driver/samsung-driver-mo.png',
                'expense/samsung-expense-mo.png',
                'health/samsung-health-mo.png',
                'superstar/samsung-superstar-mo.png',
                ],
        tab: [ 'samPop01','samPop02','samPop03','samPop04' ],
        details: [],
        pcURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/pc/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/pc/html/medical_expense_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/health_insurance/pc/html/health_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/my_superstar/pc/html/my_superstar.html',
                ],
        moURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/m/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/m/html/medical_expense_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/health_insurance/m/html/health_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/my_superstar/m/html/my_superstar.html',
                ],
        contents: [
                `운전자 플랜 가입을 위한 사이트 입니다<br/>
                PC와 모바일 따로 작업되었고 기본적으로 스크롤 위치에 따라 텍스트가 서서히 올라오며 보이는 형태입니다<br/>
                로딩가 동시에 돌아가는 숫자는 odometer.js를 사용하였고 그래프는 직접 코딩하였습니다`,
                `실손 보험 가입을 위한 사이트 입니다<br/>
                PC와 모바일 따로 작업되었고 기본적으로 스크롤 위치에 따라 텍스트가 서서히 올라오며 보이는 형태입니다<br/>
                로딩가 동시에 움직이는 그래프는 모두 직접 만들었습니다`,
                ],
    },
    {
        id: 2,
        key: 'kyobo',
        title: ['괜찮아요 암보험', '종신보험', '암케어보험', '마이데이터 A', '마이데이터 B', '마이데이터 C', '슬기로운 보험생활'],
        responsive : ['each', 'each', 'each', 'each', 'each', 'each', 'mobileOnly'],
        code: 'yes',
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['ok-cancer/kyobo-okCancer-pc.png',
                'life/kyobo-life-pc.png',
                'cancer-care/kyobo-cancer-pc.png',
                'my-data/A/kyobo-mydataA-pc.png',
                'my-data/B/kyobo-mydataB-pc.png',
                'my-data/C/kyobo-mydataC-pc.png',
                'insurance-life/kyobo-insuLife.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                'cancer-care/kyobo-cancer-mo.png',
                'my-data/A/kyobo-mydataA-mo.png',
                'my-data/B/kyobo-mydataB-mo.png',
                'my-data/C/kyobo-mydataC-mo.png',
                'insurance-life/kyobo-insuLife.png',
                ],
        pcURL: ['./code/kyobo/ok-cancer/pc/html/index.html',
                './code/kyobo/life/pc/html/index.html',
                './code/kyobo/cancer-care/pc/html/index.html',
                './code/kyobo/myDataA/pc/index.html',
                './code/kyobo/myDataB/pc/index.html',
                './code/kyobo/myDataC/pc/index.html',
                './code/kyobo/insu-life/index.html',
                ],
        moURL: ['./code/kyobo/ok-cancer/m/html/index.html',
                './code/kyobo/life/m/html/index.html',
                './code/kyobo/cancer-care/m/html/index.html',
                './code/kyobo/myDataA/m/index.html',
                './code/kyobo/myDataB/m/grand_open2.html',
                './code/kyobo/myDataC/m/index.html',
                './code/kyobo/insu-life/index.html',
                ],
    },
    {
        id: 3,
        key: 'meritz',
        title: ['해외여행자보험', '장기체류보험', '국내여행보험', '미국&북아메리카 여행자보험', '호주 여행자보험', '유럽 여행자보험', '일본 여행자보험', '필리핀 여행자보험', '태국 여행자보험', '베트남 여행자보험'],
        code: ['yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no'],
        responsive : 'both',
        day: ['5일', '1일', '1일', '1일', '1일', '1일', '1일', '1일', '1일', '1일'],
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['overseas/meritz-overseas.png',
                'long/meritz-long.png',
                'domestic/meritz-domestic.png',
                'country/mo/america.png',
                'country/mo/australia.png',
                'country/mo/europe.png',
                'country/mo/japan.png',
                'country/mo/philippines.png',
                'country/mo/thailand.png',
                'country/mo/vietnam.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                'cancer-care/kyobo-cancer-mo.png',
                ],
        pcURL: ['https://teddy10.com/travel/meritz',
                'https://teddy10.com/travel/long-term/meritz',
                'https://teddy10.com/travel/domestic/meritz',
                ],
        moURL: ['https://teddy10.com/travel/meritz',
                'https://teddy10.com/travel/long-term/meritz',
                'https://teddy10.com/travel/domestic/meritz',
                ],
    },
    {
        id: 4,
        key: 'AIG',
        title: ['여행자보험'],
        responsive : 'both',
        day: '5일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 80,
        pcImg: ['aig-pc.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                ],
    },
    {
        id: 5,
        key: 'hana',
        title: ['해외여행자보험', '장기체류보험'],
        responsive : 'both',
        day: ['5일', '2일'],
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['overseas/hana-overseas.png',
                'long/hana-long.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                ],
        pcURL: ['https://teddy10.com/travel/hanainsure',
                'https://teddy10.com/travel/long-term/hanainsure',
                ],
        moURL: ['https://teddy10.com/travel/hanainsure',
                'https://teddy10.com/travel/long-term/hanainsure',
                ],
    },
    {
        id: 6,
        key: 'kolon',
        title: ['코오롱 LSI', '코오롱 호텔', '코오롱 골프가든', '호텔 포코', '씨클라우드 호텔', '마우나오션 리조트', '금강송 에코리움'],
        responsive : 'both',
        day: ['1일', '4일', '10일', '2일', '2일', '2일', '2일'],
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: [20, 40, 100, 40, 40, 40, 40],
        pcImg: ['lsi/kolonlsi.png',
                'kolonhotel/kolonhotel.png',
                'kolongolf/kolongolf.png',
                'hotelpoco/hotelpoco.png',
                'seacloud/seacloud.png',
                'mauna/mauna.png',
                'pinestay/pinestay.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                ],
        pcURL: ['https://www.kolonlsi.com/',
                'https://www.kolonhotel.co.kr/',
                'https://www.kolongolf.com/',
                'https://hotelpoco.com/',
                'https://seacloudhotel.com/',
                'https://maunaoceanresort.co.kr/',
                'https://pinestay.com/',
                ],
    },
    {
        id: 7,
        key: 'thek',
        title: ['한국교직원공제회 웹앱'],
        responsive : 'mobileOnly',
        day: ['3일'],
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['thek01.png',
                ],
        moURL: ['https://dir.thekevent.com/',
                ],
    },
    {
        id: 8,
        key: 'aia',
        title: ['슈퍼암 이벤트 A', '슈퍼암 이벤트 B'],
        responsive : 'mobileOnly',
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['aia-a.png',
                'aia-b.png'
                ],
        moURL: ['./code/aia/A/index.html',
                './code/aia/B/index.html',
                ],
    },
    {
        id: 9,
        key: 'lg',
        title: ['사업자보험'],
        responsive : 'both',
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['lg01.png',
                ],
        pcURL: ['./code/lg/html/',],
    },
    {
        id: 10,
        key: 'teddyx',
        title: ['TEDDY X 페이지 리뉴얼'],
        responsive : 'both',
        day: '20일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['teddyx01.png',
                ],
        pcURL: ['https://teddy10.com/index.html',
                ],
    },
    {
        id: 11,
        key: 'addward',
        title: ['ADDWARD 페이지 리뉴얼'],
        responsive : 'both',
        day: '10일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['addward01.png',
                ],
        pcURL: ['https://www.addward.com/',
                ],
    },
    {
        id: 12,
        key: 'mstm',
        title: ['MSTM'],
        responsive : 'both',
        day: '1일',
        lang: 'REACT, SASS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['mstm01.png',
                ],
        pcURL: ['https://mstm.co.kr/',
                ],
    },
    {
        id: 13,
        key: 'taxin',
        title: ['택시N'],
        responsive : 'both',
        day: '1일',
        lang: 'REACT, SASS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['taxin01.png',
                ],
    },
    {
        id: 14,
        key: 'todes',
        title: ['TODES'],
        responsive : 'both',
        day: '1일',
        lang: 'REACT, SASS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['todes01.png',
                ],
        pcURL: ['https://todes.co.kr/',
        ],
    },
    {
        id: 15,
        key: 'utomo',
        title: ['UTOMO'],
        responsive : 'both',
        day: '2일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['utomo01.png',
                ],
        pcURL: ['https://www.utomo.co.kr/',
                ],
    },
]