const projects = [
    {
        id: 1,
        key: 'samsung',
        title: ['운전자플랜', '실손보험', '건강보험', '자녀보험'],
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['driver/samsung-driver-pc.png',
                'expense/samsung-expense-pc.png',
                'health/samsung-health-pc.png',
                'superstar/samsung-superstar-pc.png',
                ],
        moImg: ['driver/samsung-driver-mo.png',
                'expense/samsung-expense-mo.png',
                'health/samsung-health-mo.png',
                'superstar/samsung-superstar-mo.png',
                ],
        pcURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/pc/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/pc/html/medical_expense_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/health_insurance/pc/html/health_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/my_superstar/pc/html/my_superstar.html',
                ],
        moURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/m/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/m/html/medical_expense_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/health_insurance/m/html/health_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/my_superstar/m/html/my_superstar.html',
                ],
    },
    {
        id: 2,
        key: 'kyobo',
        title: ['괜찮아요 암보험', '종신보험', '암케어보험', '마이데이터 A', '마이데이터 B', '마이데이터 C'],
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['ok-cancer/kyobo-okCancer-pc.png',
                'life/kyobo-life-pc.png',
                'cancer-care/kyobo-cancer-pc.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                'cancer-care/kyobo-cancer-mo.png',
                ],
        pcURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/pc/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/pc/html/medical_expense_insurance.html',
                ],
        moURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/m/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/m/html/medical_expense_insurance.html',
                ],
    },
    {
        id: 3,
        key: 'kyobo',
        title: ['괜찮아요 암보험', '종신보험', '암케어보험'],
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['ok-cancer/kyobo-okCancer-pc.png',
                'life/kyobo-life-pc.png',
                'cancer-care/kyobo-cancer-pc.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                'cancer-care/kyobo-cancer-mo.png',
                ],
        pcURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/pc/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/pc/html/medical_expense_insurance.html',
                ],
        moURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/m/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/m/html/medical_expense_insurance.html',
                ],
    },
    {
        id: 4,
        key: 'kyobo',
        title: ['괜찮아요 암보험', '종신보험', '암케어보험'],
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['ok-cancer/kyobo-okCancer-pc.png',
                'life/kyobo-life-pc.png',
                'cancer-care/kyobo-cancer-pc.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                'cancer-care/kyobo-cancer-mo.png',
                ],
        pcURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/pc/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/pc/html/medical_expense_insurance.html',
                ],
        moURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/m/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/m/html/medical_expense_insurance.html',
                ],
    },
    {
        id: 5,
        key: 'kyobo',
        title: ['괜찮아요 암보험', '종신보험', '암케어보험'],
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['ok-cancer/kyobo-okCancer-pc.png',
                'life/kyobo-life-pc.png',
                'cancer-care/kyobo-cancer-pc.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                'cancer-care/kyobo-cancer-mo.png',
                ],
        pcURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/pc/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/pc/html/medical_expense_insurance.html',
                ],
        moURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/m/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/m/html/medical_expense_insurance.html',
                ],
    },
]