const projects = [
    {
        id: 1,
        key: 'samsung',
        title: ['운전자플랜', '실손보험', '건강보험', '자녀보험'],
        responsive : 'each',
        code: 'yes',
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['driver/samsung-driver-pc.png',
                'expense/samsung-expense-pc.png',
                'health/samsung-health-pc.png',
                'superstar/samsung-superstar-pc.png',
                ],
        moImg: ['driver/samsung-driver-mo.png',
                'expense/samsung-expense-mo.png',
                'health/samsung-health-mo.png',
                'superstar/samsung-superstar-mo.png',
                ],
        pcURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/pc/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/pc/html/medical_expense_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/health_insurance/pc/html/health_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/my_superstar/pc/html/my_superstar.html',
                ],
        moURL: ['https://sdp.addward.com/ad/sfmi_landing/happy_partner/m/html/happy_partner.html',
                'https://sdp.addward.com/ad/sfmi_landing/medical_expense_insurance/m/html/medical_expense_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/health_insurance/m/html/health_insurance.html',
                'https://sdp.addward.com/ad/sfmi_landing/my_superstar/m/html/my_superstar.html',
                ],
        tab: [ 'samPop01', 'samPop02', 'samPop03', 'samPop04' ],
        contents: [
                `운전자 플랜 가입을 위한 사이트입니다 
                PC와 모바일 따로 작업되었고 기본적으로 스크롤 위치에 따라 텍스트가 서서히 올라오며 보이는 형태입니다 
                로딩과 동시에 돌아가는 숫자는 odometer.js를 사용하였고 그래프는 직접 코딩하였습니다`,
                `실손 보험 가입을 위한 사이트입니다 
                PC와 모바일 따로 작업되었고 기본적으로 스크롤 위치에 따라 텍스트가 서서히 올라오며 보이는 형태입니다 
                로딩과 동시에 움직이는 그래프는 모두 직접 만들었습니다`,
                `건강 보험 가입을 위한 사이트입니다 
                PC와 모바일 따로 작업되었고 기본적으로 스크롤 위치에 따라 텍스트가 서서히 올라오며 보이는 형태입니다 
                로딩과 동시에 움직이는 그래프 및 애니메이션은 모두 직접 만들었습니다`,
                `자녀 보험 가입을 위한 사이트입니다 
                PC와 모바일 따로 작업되었고 기본적으로 스크롤 위치에 따라 텍스트가 서서히 올라오며 보이는 형태입니다 
                로딩과 동시에 움직이는 그래프는 직접 코딩하였고, 돌아가는 숫자는 odometer.js를 사용하였습니다`,
                ],
    },
    {
        id: 2,
        key: 'kyobo',
        title: ['괜찮아요 암보험', '종신보험', '암케어보험', '마이데이터 A', '마이데이터 B', '마이데이터 C', '슬기로운 보험생활'],
        responsive : ['each', 'each', 'each', 'each', 'each', 'each', 'mobileOnly'],
        code: 'yes',
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['ok-cancer/kyobo-okCancer-pc.png',
                'life/kyobo-life-pc.png',
                'cancer-care/kyobo-cancer-pc.png',
                'my-data/A/kyobo-mydataA-pc.png',
                'my-data/B/kyobo-mydataB-pc.png',
                'my-data/C/kyobo-mydataC-pc.png',
                'insurance-life/kyobo-insuLife.png',
                ],
        moImg: ['ok-cancer/kyobo-okCancer-mo.png',
                'life/kyobo-life-mo.png',
                'cancer-care/kyobo-cancer-mo.png',
                'my-data/A/kyobo-mydataA-mo.png',
                'my-data/B/kyobo-mydataB-mo.png',
                'my-data/C/kyobo-mydataC-mo.png',
                'insurance-life/kyobo-insuLife.png',
                ],
        pcURL: ['./code/kyobo/ok-cancer/pc/html/index.html',
                './code/kyobo/life/pc/html/index.html',
                './code/kyobo/cancer-care/pc/html/index.html',
                './code/kyobo/myDataA/pc/index.html',
                './code/kyobo/myDataB/pc/index.html',
                './code/kyobo/myDataC/pc/index.html',
                './code/kyobo/insu-life/index.html',
                ],
        moURL: ['./code/kyobo/ok-cancer/m/html/index.html',
                './code/kyobo/life/m/html/index.html',
                './code/kyobo/cancer-care/m/html/index.html',
                './code/kyobo/myDataA/m/index.html',
                './code/kyobo/myDataB/m/grand_open2.html',
                './code/kyobo/myDataC/m/index.html',
                './code/kyobo/insu-life/index.html',
                ],
        tab: [ 'kyoPop01', 'kyoPop02', 'kyoPop03', 'kyoPop04', 'kyoPop05', 'kyoPop06', 'kyoPop07' ],
        contents: [
                `암보험 가입을 위한 사이트입니다 PC와 모바일 따로 작업되었고 첫 화면만 애니메이션이 들어가 있습니다`,
                `종신보험 가입을 위한 사이트입니다 PC와 모바일 따로 작업되었고 첫 화면만 애니메이션이 들어가 있습니다`,
                `암케어보험 가입을 위한 사이트입니다 PC와 모바일 따로 작업되었고 첫 화면만 애니메이션이 들어가 있습니다`,
                `마이데이터 가입을 위한 사이트입니다 PC와 모바일 따로 작업되었고 기본적으로 스크롤 위치에 따라 텍스트가 서서히 올라오며 보이는 형태입니다`,
                `마이데이터 가입을 위한 사이트입니다 PC와 모바일 따로 작업되었고 원 페이지 형식으로 보여지는 사이트입니다`,
                `마이데이터 가입을 위한 사이트입니다 PC와 모바일 따로 작업되었고 기본적으로 스크롤 위치에 따라 텍스트가 서서히 올라오며 보이는 형태입니다`,
                `자녀보험 안내사이트입니다 모바일만 작업하였으며 swiper.js를 사용하여, 슬라이드로 한 페이지씩 보여지는 사이트입니다`,
                ],
    },
    {
        id: 3,
        key: 'meritz',
        title: ['해외여행자보험', '장기체류보험', '국내여행보험', '미국&북아메리카 여행자보험', '호주 여행자보험', '유럽 여행자보험', '일본 여행자보험', '필리핀 여행자보험', '태국 여행자보험', '베트남 여행자보험'],
        code: ['yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no'],
        responsive : 'both',
        day: ['5일', '1일', '1일', '1일', '1일', '1일', '1일', '1일', '1일', '1일'],
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['overseas/meritz-overseas.png',
                'long/meritz-long.png',
                'domestic/meritz-domestic.png',
                'country/pc/america.png',
                'country/pc/australia.png',
                'country/pc/europe.png',
                'country/pc/japan.png',
                'country/pc/philippines.png',
                'country/pc/thailand.png',
                'country/pc/vietnam.png',
                ],
        moImg: ['overseas/meritz-overseas.png',
                'long/meritz-long.png',
                'domestic/meritz-domestic.png',
                'country/mo/america.png',
                'country/mo/australia.png',
                'country/mo/europe.png',
                'country/mo/japan.png',
                'country/mo/philippines.png',
                'country/mo/thailand.png',
                'country/mo/vietnam.png',
                ],
        pcURL: ['https://teddy10.com/travel/meritz',
                'https://teddy10.com/travel/long-term/meritz',
                'https://teddy10.com/travel/domestic/meritz',
                ],
        tab: [ 'mePop01', 'mePop02', 'mePop03', 'mePop04', 'mePop05', 'mePop061', 'mePop07', 'mePop08', 'mePop09', 'mePop10' ],
        contents: [
                `해외 여행 보험 가입을 위한 사이트입니다 반응형으로 제작되었으며 모든 가입 프로세스도 직접 작업하였습니다`,
                `해외 장기체류 보험 가입을 위한 사이트입니다 반응형으로 제작되었으며 모든 가입 프로세스도 직접 작업하였습니다`,
                `국내 여행 보험 가입을 위한 사이트입니다 반응형으로 제작되었으며 모든 가입 프로세스도 직접 작업하였습니다`,
                `특정 국가 여행객을 유입하기 위한 사이트입니다 코드가 유실되어 사진으로만 남아있습니다 모바일은 아래 아이콘 영역을 swiper.js로 슬라이드 효과를 주었습니다`,
                `특정 국가 여행객을 유입하기 위한 사이트입니다 코드가 유실되어 사진으로만 남아있습니다 모바일은 아래 아이콘 영역을 swiper.js로 슬라이드 효과를 주었습니다`,
                `특정 국가 여행객을 유입하기 위한 사이트입니다 코드가 유실되어 사진으로만 남아있습니다 모바일은 아래 아이콘 영역을 swiper.js로 슬라이드 효과를 주었습니다`,
                `특정 국가 여행객을 유입하기 위한 사이트입니다 코드가 유실되어 사진으로만 남아있습니다 모바일은 아래 아이콘 영역을 swiper.js로 슬라이드 효과를 주었습니다`,
                `특정 국가 여행객을 유입하기 위한 사이트입니다 코드가 유실되어 사진으로만 남아있습니다 모바일은 아래 아이콘 영역을 swiper.js로 슬라이드 효과를 주었습니다`,
                `특정 국가 여행객을 유입하기 위한 사이트입니다 코드가 유실되어 사진으로만 남아있습니다 모바일은 아래 아이콘 영역을 swiper.js로 슬라이드 효과를 주었습니다`,
                `특정 국가 여행객을 유입하기 위한 사이트입니다 코드가 유실되어 사진으로만 남아있습니다 모바일은 아래 아이콘 영역을 swiper.js로 슬라이드 효과를 주었습니다`,
                ],
    },
    {
        id: 4,
        key: 'AIG',
        title: ['여행자보험'],
        responsive : 'both',
        day: '5일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 80,
        pcImg: ['aig-pc.png'],
        moImg: ['aig-pc.png'],
        tab: [ 'aig01'],
        contents: [`해외 여행 보험 가입을 위한 사이트입니다 반응형으로 제작되었으며 모든 가입 프로세스도 직접 작업하였습니다 코드가 유실되어 사진으로만 남아있습니다`],
    },
    {
        id: 5,
        key: 'hana',
        title: ['해외여행자보험', '장기체류보험'],
        responsive : 'both',
        day: ['5일', '2일'],
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['overseas/hana-overseas.png',
                'long/hana-long.png',
                ],
        moImg: ['overseas/hana-overseas.png',
                'long/hana-long.png',
                ],
        pcURL: ['https://teddy10.com/travel/hanainsure',
                'https://teddy10.com/travel/long-term/hanainsure',
                ],
        tab: [ 'hana01', 'hana02' ],
        contents: [
                `해외 여행 보험 가입을 위한 사이트입니다 반응형으로 제작되었으며 모든 가입 프로세스도 직접 작업하였습니다`,
                `해외 여행 보험 가입을 위한 사이트입니다 반응형으로 제작되었으며 모든 가입 프로세스도 직접 작업하였습니다`,
                ],
    },
    {
        id: 6,
        key: 'kolon',
        title: ['코오롱 LSI', '코오롱 호텔', '코오롱 골프가든', '호텔 포코', '씨클라우드 호텔', '마우나오션 리조트', '금강송 에코리움'],
        responsive : 'both',
        day: ['1일', '4일', '10일', '2일', '2일', '2일', '2일'],
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: [20, 40, 100, 40, 40, 40, 40],
        pcImg: ['lsi/kolonlsi.png',
                'kolonhotel/kolonhotel.png',
                'kolongolf/kolongolf.png',
                'hotelpoco/hotelpoco.png',
                'seacloud/seacloud.png',
                'mauna/mauna.png',
                'pinestay/pinestay.png',
                ],
        moImg: ['lsi/kolonlsi.png',
                'kolonhotel/kolonhotel.png',
                'kolongolf/kolongolf.png',
                'hotelpoco/hotelpoco.png',
                'seacloud/seacloud.png',
                'mauna/mauna.png',
                'pinestay/pinestay.png',
                ],
        pcURL: ['https://www.kolonlsi.com/',
                'https://www.kolonhotel.co.kr/',
                'https://www.kolongolf.com/',
                'https://hotelpoco.com/',
                'https://seacloudhotel.com/',
                'https://maunaoceanresort.co.kr/',
                'https://pinestay.com/',
                ],
        tab: [ 'kolon01', 'kolon02', 'kolon03', 'kolon04', 'kolon05', 'kolon06', 'kolon07' ],
        contents: [
                `기업 소개 페이지 입니다 웹 에디터로 제작되어 있던 걸 전달받아 내용 추가 및 수정 사항을 적용했습니다`,
                `호텔 소개 페이지 입니다 기존에 제작되어 있던 걸 전달받아 내용 추가 및 수정 사항을 적용했습니다`,
                `골프장 소개 페이지 입니다 기존 호텔과 동일한 디자인으로 처음부터 끝까지 제작하였으며 다른 호텔과는 조금 다른 디자인의 수정 사항이 있어 적용하였습니다 골프장 회원∙부킹 관련 페이지도 모두 새로 작업하였습니다`,
                `호텔 소개 페이지 입니다 기존에 제작되어 있던 걸 전달받아 내용 추가 및 수정 사항을 적용했습니다`,
                `호텔 소개 페이지 입니다 기존에 제작되어 있던 걸 전달받아 내용 추가 및 수정 사항을 적용했습니다`,
                `호텔 소개 페이지 입니다 기존에 제작되어 있던 걸 전달받아 내용 추가 및 수정 사항을 적용했습니다`,
                `호텔 소개 페이지 입니다 기존에 제작되어 있던 걸 전달받아 내용 추가 및 수정 사항을 적용했습니다`,
                ],
    },
    {
        id: 7,
        key: 'thek',
        title: ['한국교직원공제회 웹앱'],
        responsive : 'mobileOnly',
        day: ['3일'],
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['thek01.png'],
        moURL: ['https://dir.thekevent.com/'],
        tab: ['thek01'],
        contents: [`교직원 전용 앱입니다 모바일 전용으로 작업되어 있습니다`],
    },
    {
        id: 8,
        key: 'aia',
        title: ['슈퍼암 이벤트 A', '슈퍼암 이벤트 B'],
        responsive : 'mobileOnly',
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['aia-a.png',
                'aia-b.png'
                ],
        moURL: ['./code/aia/A/index.html',
                './code/aia/B/index.html',
                ],
        tab: ['aia01', 'aia02'],
        contents: [`AIA 홍보용 배너 페이지입니다 모바일 전용으로 작업되어 있습니다`,`AIA 홍보용 배너 페이지입니다 모바일 전용으로 작업되어 있습니다`],
    },
    {
        id: 9,
        key: 'lg',
        title: ['사업자보험'],
        responsive : 'both',
        day: '1일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['lg01.png'],
        pcURL: ['./code/lg/html/'],
        tab: ['lg01'],
        contents: [`LG 비즈마켓 전용 사이트입니다 반응형으로 제작되었지만 PC와 모바일 화면만 중점으로 작업하였습니다`],
    },
    {
        id: 10,
        key: 'teddyx',
        title: ['TEDDY X 리뉴얼'],
        responsive : 'both',
        day: '20일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['teddyx01.png'],
        pcURL: ['https://teddy10.com/index.html'],
        tab: ['teddyx01'],
        contents: [`보험 판매 대행 사이트입니다 기존에 있던 사이트를 새로 리뉴얼 작업하였습니다`],
    },
    {
        id: 11,
        key: 'addward',
        title: ['ADDWARD 리뉴얼'],
        responsive : 'both',
        day: '10일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['addward01.png'],
        pcURL: ['https://www.addward.com/'],
        tab: ['addward01'],
        contents: [`마케팅 회사 사이트입니다 기존에 있던 사이트를 새로 리뉴얼 작업하였습니다 움직이는 영상은 이미지 파일을 빠르게 돌려가며 영상처럼 보이게 작업하였습니다`],
    },
    {
        id: 12,
        key: 'mstm',
        title: ['MSTM'],
        responsive : 'both',
        day: '1일',
        lang: 'REACT, SASS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['mstm01.png'],
        pcURL: ['https://mstm.co.kr/'],
        tab: ['mstm01'],
        contents: [`리액트로 진행한 사이트입니다  swiper.js를 사용한 원페이지 사이트입니다`],
    },
    {
        id: 13,
        key: 'taxin',
        title: ['택시N'],
        responsive : 'both',
        day: '1일',
        lang: 'REACT, SASS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['taxin01.png'],
        tab: ['taxin01'],
        contents: [`리액트로 진행한 사이트입니다 swiper.js를 사용한 원페이지 사이트입니다 코드가 유실되어 사진으로만 남아있습니다`],
    },
    {
        id: 14,
        key: 'todes',
        title: ['TODES'],
        responsive : 'both',
        day: '1일',
        lang: 'REACT, SASS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['todes01.png'],
        pcURL: ['https://todes.co.kr/'],
        tab: ['todes01'],
        contents: [`리액트로 진행한 사이트입니다 스크롤에 따라 위로 노출되는 형식의 애니메이션이 적용되어 있습니다`],
    },
    {
        id: 15,
        key: 'utomo',
        title: ['UTOMO'],
        responsive : 'both',
        day: '2일',
        lang: 'HTML, CSS, JAVASCRIPT',
        percentage: 100,
        pcImg: ['utomo01.png'],
        pcURL: ['https://www.utomo.co.kr/'],
        tab: ['utomo01'],
        contents: [`스크롤에 따라 다양하게 노출되는 형식의 애니메이션이 적용되어 있는 사이트입니다`],
    },
]